### ISSUE TITLE
Unable to parse JSON with bulk_summary_ip()

### ISSUE THREAD

**Issue by MaxouPicsou** [sebdraven/pyonyphe#7]
I try to run the code below but I have the following error:
```
from onyphe import Onyphe

API_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
api = Onyphe(API_KEY)

summary_result = api.bulk_summary_ip("list.txt")
```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyonyphe-2.0-py3.8.egg/onyphe/client.py", line 71, in _request
  File "/usr/lib/python3/dist-packages/requests/models.py", line 888, in json
    return complexjson.loads(
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 2 column 1 - line 116 column 1 (char 1932 - 117500)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    summary_result = api.bulk_summary_ip("list")
  File "/usr/local/lib/python3.8/dist-packages/pyonyphe-2.0-py3.8.egg/onyphe/client.py", line 433, in bulk_summary_ip
  File "/usr/local/lib/python3.8/dist-packages/pyonyphe-2.0-py3.8.egg/onyphe/client.py", line 98, in _prepare_request
  File "/usr/local/lib/python3.8/dist-packages/pyonyphe-2.0-py3.8.egg/onyphe/client.py", line 75, in _request
onyphe.exception.APIError: Unable to parse JSON
```

My file _list.txt_ contains ip addresses (one per line) and works with onyphe API. It seems to be a json parse error. It is possible that error concers all bulk methods.

**Comment by sebdraven** [comment]
Hi, 

I retry it with my file

![image](https://user-images.githubusercontent.com/1478484/157214952-3dedd595-34a7-4d22-bc69-ff42aaa49289.png)

And I've no errors.

**Comment by MaxouPicsou** [comment]
I retry it on jupyter-notebook as you and I have the output for the first address but the error is raised for the second and appears at the end of the output:

![image](https://user-images.githubusercontent.com/47140883/157223203-82e6762a-5e5e-44c8-a328-91f9c2235e81.png)

![image](https://user-images.githubusercontent.com/47140883/157223277-cf420d06-a60a-4c4c-9520-07ba03648090.png)

Do you have the same thing?

**Comment by sebdraven** [comment]
it's possible to share the address when the parser crashes ?

**Comment by sebdraven** [comment]
You can test after pull the repo like that ?  `for res in client_onyphe.bulk_summary_ip('ips.txt'):
    print(res)`

**Comment by sebdraven** [comment]
yeah ! Thank for your report ! I close this issue ! Have a fun !
